// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQde3GFuMjjWCtPzKgpPJtcCeH5Z01YKQ',
    appId: '1:574904341275:web:1daef5db9843180277f9be',
    messagingSenderId: '574904341275',
    projectId: 'budgetly-84048',
    authDomain: 'budgetly-84048.firebaseapp.com',
    storageBucket: 'budgetly-84048.firebasestorage.app',
    measurementId: 'G-KL7BNGVNGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwo07XIaev7KQJOjW2H22M9F2JZhwlUs',
    appId: '1:574904341275:android:b8da66ac242e597177f9be',
    messagingSenderId: '574904341275',
    projectId: 'budgetly-84048',
    storageBucket: 'budgetly-84048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_T1ogYFqDzv52-qNV19sDi4PFtvD-a0',
    appId: '1:574904341275:ios:7650407ab0be23d477f9be',
    messagingSenderId: '574904341275',
    projectId: 'budgetly-84048',
    storageBucket: 'budgetly-84048.firebasestorage.app',
    iosBundleId: 'com.example.budgetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_T1ogYFqDzv52-qNV19sDi4PFtvD-a0',
    appId: '1:574904341275:ios:7650407ab0be23d477f9be',
    messagingSenderId: '574904341275',
    projectId: 'budgetly-84048',
    storageBucket: 'budgetly-84048.firebasestorage.app',
    iosBundleId: 'com.example.budgetly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQde3GFuMjjWCtPzKgpPJtcCeH5Z01YKQ',
    appId: '1:574904341275:web:a63b9da2f82bcee477f9be',
    messagingSenderId: '574904341275',
    projectId: 'budgetly-84048',
    authDomain: 'budgetly-84048.firebaseapp.com',
    storageBucket: 'budgetly-84048.firebasestorage.app',
    measurementId: 'G-4FFZYS8VB1',
  );
}
